# Main configuration
app_config:
  environments:
    development:
      database:
        host: localhost
        port: 5432
        max_connections: 100
        shared_buffers: "256MB"
        effective_cache_size: "1GB"
    production:
      database:
        host: ${DB_HOST}
        port: ${DB_PORT}
        max_connections: ${DB_MAX_CONNECTIONS:-200}
        shared_buffers: ${DB_SHARED_BUFFERS:-"1GB"}
        effective_cache_size: ${DB_CACHE_SIZE:-"4GB"}
  awx_settings:
    url: ${AWX_URL:-"http://localhost:8052"}
    user: ${AWX_ADMIN_USER:-"admin"}
    password: ${AWX_ADMIN_PASSWORD} # Moved to environment variable
    api_version: "v2"
    defaults:
      job_timeout: ${AWX_JOB_TIMEOUT:-3600}
      max_failures: ${AWX_MAX_FAILURES:-3}
      execution_nodes: ${AWX_EXECUTION_NODES:-["node1", "node2"]}
      concurrent_jobs: ${AWX_CONCURRENT_JOBS:-10}
  system:
    paths:
      playbooks: ${PLAYBOOKS_PATH:-"/ansible/playbooks"}
      inventory: ${INVENTORY_PATH:-"/ansible/inventory.ini"}
      logs: ${LOGS_PATH:-"/var/log/ansible-runner"}
      config: ${CONFIG_PATH:-"/etc/ansible/config.yaml"}
      awx_data: ${AWX_DATA_PATH:-"/opt/awx/data"}
    logging:
      level: ${LOG_LEVEL:-"INFO"}
      format: ${LOG_FORMAT:-"[%(asctime)s] [%(levelname)s] %(message)s"}
      retention_days: ${LOG_RETENTION:-7}
      handlers:
        file:
          enabled: true
          path: ${LOG_FILE_PATH:-"/var/log/awx.log"}
        syslog:
          enabled: ${SYSLOG_ENABLED:-false}
          facility: ${SYSLOG_FACILITY:-"local0"}
    security:
      enforce_ssl: ${ENFORCE_SSL:-true}
      secure_cookies: ${SECURE_COOKIES:-true}
      allowed_hosts: ${ALLOWED_HOSTS:-["localhost"]}
      cors_origins: ${CORS_ORIGINS:-[]}
      rate_limit:
        enabled: ${RATE_LIMIT_ENABLED:-true}
        requests_per_minute: ${RATE_LIMIT_RPM:-60}
    network:
      proxy_enabled: ${PROXY_ENABLED:-false}
      proxy_url: ${PROXY_URL:-""}
      proxy_port: ${PROXY_PORT:-""}
      timeout: ${NETWORK_TIMEOUT:-30}
      retries: ${NETWORK_RETRIES:-3}
# Common configurations
common:
  logging:
    level: ${LOG_LEVEL:-info}
dependencies:
  required:
    - ansible>=${ANSIBLE_VERSION:-"2.9"}
    - sshpass
    - dialog
    - whiptail
    - curl
    - python3-yaml
    - jq
    - postgresql-client
  optional:
    - git
    - rsync
    - zip
display:
  colors:
    success: "\033[0;32m"
    error: "\033[0;31m"
    warning: "\033[0;33m"
    info: "\033[0;34m"
    reset: "\033[0m"
paths:
  logs: "/var/log"
  config: "/opt/awx/config.yaml"
