paths:
  playbooks: "/ansible/playbooks"
  inventory: "/ansible/inventory.ini"
  logs: "/var/log/ansible"
dependencies:
  required:
    - ansible
    - sshpass
    - python3-yaml
    - jq
    - curl
logging:
  level: "INFO"
  retention_days: 7
