version: "3.8"

services:
  awx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: awx
    restart: unless-stopped
    environment:
      - AWX_VERSION=24.6.0
      - AWX_DB_HOST=awx_postgres
      - AWX_DB_PORT=5432
      - AWX_DB_NAME=awx
      - AWX_DB_USER=awx
      - AWX_DB_PASSWORD=awx_password
    depends_on:
      awx_postgres:
        condition: service_healthy
    ports:
      - "8052:8052"
    networks:
      - awx_network
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./inventory.ini:/opt/awx/installer/inventory
    command: ["/bin/bash", "-c", "chmod +x /entrypoint.sh && /entrypoint.sh"]

  awx_postgres:
    image: postgres:14
    container_name: awx_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=awx
      - POSTGRES_USER=awx
      - POSTGRES_PASSWORD=awx_password
    networks:
      - awx_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "awx", "-d", "awx"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  awx_network:
    driver: bridge

volumes:
  postgres_data:
