services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible_controller
    volumes:
      - .:/ansible:rw
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /ansible
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash", "/ansible/interactive_ansible.sh"]
    environment:
      - TERM=xterm
      - ANSIBLE_HOST_KEY_CHECKING=False
      - TZ=UTC
      - ANSIBLE_FORCE_COLOR=1
      - PYTHONUNBUFFERED=1
    networks:
      ansible_network:
        ipv4_address: 172.28.0.100
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  ansible_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
