services:
  ansible_runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible_runner
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./playbooks:/ansible/playbooks
      - ./inventory.ini:/ansible/inventory.ini
      - ./config.yaml:/ansible/config.yaml
      - ./logs:/var/log/ansible
      - ./ssh/id_rsa:/root/.ssh/id_rsa:ro
    working_dir: /ansible
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./webui:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ansible_runner
