version: "3.8"

services:
  awx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: awx_controller
    restart: unless-stopped
    ports:
      - "127.0.0.1:8052:8052"  # Bind to localhost only
    volumes:
      - type: volume
        source: awx_data
        target: /var/lib/postgresql/data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    environment:
      - TERM=xterm
      - ANSIBLE_HOST_KEY_CHECKING=False
      - ANSIBLE_FORCE_COLOR=1
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    env_file: .env
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8052/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    networks:
      awx_network:
        ipv4_address: 172.28.0.100

volumes:
  awx_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind

networks:
  awx_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
    driver_opts:
      com.docker.network.bridge.name: awx_net
