services:
  awx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: awx
    restart: unless-stopped
    environment:
      - AWX_VERSION=24.6.0
      - AWX_DB_HOST=awx_postgres
      - AWX_DB_PORT=5432
      - AWX_DB_NAME=awx
      - AWX_DB_USER=awx
      - AWX_DB_PASSWORD=${AWX_DB_PASSWORD:?Database password not set}
    depends_on:
      awx_postgres:
        condition: service_healthy
    ports:
      - "127.0.0.1:8052:8052" # Restrict to localhost
    networks:
      - awx_network
    volumes:
      - type: bind
        source: ./entrypoint.sh
        target: /entrypoint.sh
      - type: bind
        source: ./utils.sh
        target: /opt/awx/utils.sh
      - type: bind
        source: ./inventory.ini
        target: /opt/awx/installer/inventory
      - type: bind
        source: ./config.yaml
        target: /opt/awx/config.yaml
    command: ["/bin/bash", "-c", "chmod +x /entrypoint.sh && /entrypoint.sh"]
    security_opt:
      - no-new-privileges:true

  awx_postgres:
    image: postgres:14-alpine # Using alpine for smaller image
    container_name: awx_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=awx
      - POSTGRES_USER=awx
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?Database password not set}
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    networks:
      - awx_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U awx -d awx"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  awx_network:
    driver: bridge
