services:
  postgres:
    image: postgres:14
    container_name: awx_postgres
    restart: always
    environment:
      POSTGRES_DB: awx
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - awx_network

  awx:
    build: .
    container_name: awx
    restart: always
    depends_on:
      - postgres
    ports:
      - "8052:8052"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: awx
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpassword
    networks:
      - awx_network

volumes:
  postgres_data:

networks:
  awx_network:
    driver: bridge
