version: "3.9"

services:
  ansible_runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible_runner
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./playbooks:/ansible/playbooks
      - ./inventory.ini:/ansible/inventory.ini
      - ./config.yaml:/ansible/config.yaml
      - ./logs:/var/log/ansible
      - ./ssh/id_rsa:/root/.ssh/id_rsa:ro
    working_dir: /ansible
    command: tail -f /var/log/ansible/ansible.log
    ports:
      - "5000:5000"
      - "2222:22"
