- name: Check Disk Space Usage
  hosts: all
  vars:
    disk_threshold: 80 # Threshold percentage
  tasks:
    - name: Get disk space information
      shell: df -h / | tail -n 1 | awk '{print $5}' | sed 's/%//'
      register: disk_usage
      ignore_errors: true
    - name: Parse disk usage
      set_fact:
        usage_percent: "{{ disk_usage.stdout | int }}"
    - name: Display detailed disk information
      shell: df -h /
      register: disk_details
    - name: Show disk usage details
      debug:
        msg: |
          Disk Usage Details:
          {{ disk_details.stdout_lines | join('\n  ') }}
          Current Usage: {{ usage_percent }}%
          Threshold: {{ disk_threshold }}%
    - name: Alert on high disk usage
      debug:
        msg: "WARNING: Disk usage is critical on {{ inventory_hostname }}!"
      when: usage_percent | int > disk_threshold | int
    - name: Fail when disk space exceeds threshold
      fail:
        msg: "Disk space usage ({{ usage_percent }}%) exceeds threshold ({{ disk_threshold }}%)"
      when: usage_percent | int > disk_threshold | int
