# This playbook creates and maintains system documentation by gathering system information
# and creating structured documentation files in a designated directory

- name: Maintain System Documentation
  hosts: localhost
  become: true
  # Define variables for documentation directory and ownership
  vars:
    docs_path: /var/system_docs
    docs_owner: root
    docs_group: root
  tasks:
    # Create base directory for documentation storage
    - name: Ensure documentation directory exists
      file:
        path: "{{ docs_path }}"
        state: directory
        mode: '0755'
        owner: "{{ docs_owner }}"
        group: "{{ docs_group }}"
    # Collect and store basic system information including kernel version,
    # distribution details, and OS release information
    - name: Gather system information
      shell: |
        echo "System Information" > {{ docs_path }}/system_info.txt
        uname -a >> {{ docs_path }}/system_info.txt
        lsb_release -a >> {{ docs_path }}/system_info.txt 2>/dev/null || cat /etc/os-release >> {{ docs_path }}/system_info.txt
      args:
        executable: /bin/bash
        creates: "{{ docs_path }}/system_info.txt"
    # Create a markdown index file that serves as documentation homepage
    # and provides navigation to other documentation files
    - name: Create documentation index
      copy:
        dest: "{{ docs_path }}/index.md"
        content: |
          # System Documentation

          This directory contains system documentation and configuration details.

          ## Contents
          - system_info.txt: Basic system information
          - inventory.txt: System inventory
        mode: '0644'
        owner: "{{ docs_owner }}"
        group: "{{ docs_group }}"
    # Generate inventory file using a custom template
    # This task is allowed to fail (ignore_errors) if template is missing
    - name: Create system inventory file
      template:
        src: inventory_template.j2
        dest: "{{ docs_path }}/inventory.txt"
        mode: '0644'
        owner: "{{ docs_owner }}"
        group: "{{ docs_group }}"
      ignore_errors: true
