# Playbook: System Troubleshooting and Diagnostics
# Purpose: Gather comprehensive system health information and display a status report
- name: Enhanced System Troubleshooting
  hosts: all
  gather_facts: true
  tasks:
    # Check system logs for critical errors (priority 3)
    - name: Check system logs for errors
      command: journalctl -p 3 -xb --no-pager -n 50
      register: logs_output
      ignore_errors: true
    # Filesystem usage information
    - name: Check disk space
      shell: df -h
      register: disk_space
      ignore_errors: true
    # Memory statistics including used, free, and cached memory
    - name: Check memory usage
      shell: free -m
      register: memory_usage
      ignore_errors: true
    # System load averages for 1, 5, and 15 minutes
    - name: Check system load
      shell: uptime
      register: system_load
      ignore_errors: true
    # Basic network connectivity test using Google DNS
    - name: Check network connectivity
      ping:
        dest: "8.8.8.8"
      register: network_check
      ignore_errors: true
    # Gather information about system services
    - name: Check critical services status
      service_facts:
      register: service_status
      ignore_errors: true
    # Format and display collected information in a readable format
    - name: Display system status report
      debug:
        msg: |
          # System Status Report
          # Generated by Ansible
          # ===================

          ## Disk Space Usage:
          {{ disk_space.stdout_lines | default(['No data available']) | join('\n') }}

          ## Memory Statistics:
          {{ memory_usage.stdout_lines | default(['No data available']) | join('\n') }}

          ## System Load Information:
          {{ system_load.stdout_lines | default(['No data available']) | join('\n') }}

          ## Network Connectivity Status:
          {{ network_check.ping | default('Network check failed') }}

          ## Recent Critical System Errors:
          {{ logs_output.stdout_lines | default(['No errors found']) | join('\n') }}
