# Playbook: System Troubleshooting and Diagnostics
# Purpose: Gather comprehensive system health information and display a status report
- name: Enhanced System Troubleshooting
  hosts: all
  gather_facts: true
  tasks:
    # Check system logs for critical errors (priority 3)
    - name: Check system logs for errors
      command: journalctl -p 3 -xb --no-pager -n 50
      register: logs_output
      ignore_errors: true
    # Filesystem usage information
    - name: Check disk space
      shell: df -h
      register: disk_space
      ignore_errors: true
    # Memory statistics including used, free, and cached memory
    - name: Check memory usage
      shell: free -m
      register: memory_usage
      ignore_errors: true
    # System load averages for 1, 5, and 15 minutes
    - name: Check system load
      shell: uptime
      register: system_load
      ignore_errors: true
    # Basic network connectivity test using Google DNS
    - name: Check network connectivity
      ping:
        dest: "8.8.8.8"
      register: network_check
      ignore_errors: true
    # Gather information about system services
    - name: Check critical services status
      service_facts:
      register: service_status
      ignore_errors: true
    # Format and display collected information in a readable format
  - name: Display system status report
    debug:
      msg: |
        # System Status Report
        Logs (last 50 critical messages):
        {{ logs_output.stdout | default('No critical logs') }}

        Disk Space:
        {{ disk_space.stdout | default('N/A') }}

        Memory Usage:
        {{ memory_usage.stdout | default('N/A') }}

        System Load:
        {{ system_load.stdout | default('N/A') }}

        Network Connectivity: {{ 'OK' if network_check is not failed else 'FAILED' }}

        Services:
        {{ service_status.services | default('N/A') }}
